const { jsPDF } = window.jspdf;

document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('billForm');
    const dateInput = document.getElementById('date');
    const tenantNameInput = document.getElementById('tenantName');
    const lastReadingInput = document.getElementById('lastReading');
    const currentReadingInput = document.getElementById('currentReading');
    const resultSection = document.getElementById('resultSection');
    const downloadPdfBtn = document.getElementById('downloadPdf');
    const whatsappShareBtn = document.getElementById('whatsappShare');
    const closeBtn = document.getElementById('closeBtn');

    let currentBillData = {};

    dateInput.value = new Date().toISOString().split('T')[0];

    function formatDate(dateStr) {
        const date = new Date(dateStr);
        const day = String(date.getDate()).padStart(2, '0');
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const year = date.getFullYear();
        return `${day}/${month}/${year}`;
    }

    function getLastMonth(dateStr) {
        const date = new Date(dateStr);
        const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 
                          'July', 'August', 'September', 'October', 'November', 'December'];
        date.setMonth(date.getMonth() - 1);
        return monthNames[date.getMonth()] + ' ' + date.getFullYear();
    }

    function calculateBill(m1, m2) {
        const diffUnit = m2 - m1;
        const electricityCost = diffUnit * 10;
        const fixedCharge = 200;
        const totalBill = electricityCost + fixedCharge;
        
        return {
            diffUnit,
            electricityCost,
            fixedCharge,
            totalBill
        };
    }

    function displayResult(billData) {
        document.getElementById('electricityCost').textContent = `₹${billData.electricityCost}`;
        document.getElementById('totalBill').textContent = `₹${billData.totalBill}`;
        
        resultSection.classList.remove('hidden');
        resultSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }

    function clearForm() {
        form.reset();
        dateInput.value = new Date().toISOString().split('T')[0];
        resultSection.classList.add('hidden');
        currentBillData = {};
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    function showError(message) {
        const existingError = document.querySelector('.error-message');
        if (existingError) {
            existingError.remove();
        }
        
        const errorDiv = document.createElement('div');
        errorDiv.className = 'error-message show';
        errorDiv.textContent = message;
        
        form.insertBefore(errorDiv, form.firstChild);
        
        setTimeout(() => {
            errorDiv.classList.remove('show');
            setTimeout(() => errorDiv.remove(), 300);
        }, 4000);
    }

    function generatePdf() {
        const doc = new jsPDF();
        
        const lastMonthStr = getLastMonth(currentBillData.date);
        
        doc.setFontSize(24);
        doc.setTextColor(37, 99, 235);
        doc.text('Electricity Bill for ' + lastMonthStr, 105, 25, { align: 'center' });
        
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(0.5);
        doc.line(20, 32, 190, 32);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139);
        doc.text('Bill Details', 20, 50);
        
        doc.setFontSize(11);
        doc.setTextColor(30, 41, 59);
        
        doc.text('Date: ' + currentBillData.formattedDate, 20, 65);
        doc.text('Tenant Name: ' + currentBillData.tenantName, 20, 78);
        
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 90, 190, 90);
        
        doc.text('Electricity Cost:', 20, 105);
        doc.text('Rs. ' + String(currentBillData.electricityCost), 150, 105, { align: 'right' });
        
        doc.text('Fixed Charge (Water):', 20, 118);
        doc.text('Rs. 200', 150, 118, { align: 'right' });
        
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 130, 190, 130);
        
        doc.setFontSize(14);
        doc.setTextColor(37, 99, 235);
        doc.text('Total Bill Amount:', 20, 145);
        doc.text('Rs. ' + String(currentBillData.totalBill), 150, 145, { align: 'right' });
        
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text('Generated by Electricity Bill Calculator', 105, 170, { align: 'center' });
        
        doc.save('Electricity_Bill_' + currentBillData.tenantName.replace(/\s+/g, '_') + '.pdf');
    }

    async function shareOnWhatsApp() {
        const doc = new jsPDF();
        
        const lastMonthStr = getLastMonth(currentBillData.date);
        
        doc.setFontSize(24);
        doc.setTextColor(37, 99, 235);
        doc.text('Electricity Bill for ' + lastMonthStr, 105, 25, { align: 'center' });
        
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(0.5);
        doc.line(20, 32, 190, 32);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139);
        doc.text('Bill Details', 20, 50);
        
        doc.setFontSize(11);
        doc.setTextColor(30, 41, 59);
        
        doc.text('Date: ' + currentBillData.formattedDate, 20, 65);
        doc.text('Tenant Name: ' + currentBillData.tenantName, 20, 78);
        
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 90, 190, 90);
        
        doc.text('Electricity Cost:', 20, 105);
        doc.text('Rs. ' + String(currentBillData.electricityCost), 150, 105, { align: 'right' });
        
        doc.text('Fixed Charge (Water):', 20, 118);
        doc.text('Rs. 200', 150, 118, { align: 'right' });
        
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 130, 190, 130);
        
        doc.setFontSize(14);
        doc.setTextColor(37, 99, 235);
        doc.text('Total Bill Amount:', 20, 145);
        doc.text('Rs. ' + String(currentBillData.totalBill), 150, 145, { align: 'right' });
        
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text('Generated by Electricity Bill Calculator', 105, 170, { align: 'center' });

        const pdfBlob = doc.output('blob');
        const pdfFile = new File([pdfBlob], 'Electricity_Bill_' + currentBillData.tenantName.replace(/\s+/g, '_') + '.pdf', { type: 'application/pdf' });
        
        if (navigator.share && navigator.canShare({ files: [pdfFile] })) {
            try {
                await navigator.share({
                    files: [pdfFile],
                    title: 'Electricity Bill',
                    text: 'Electricity Bill for ' + currentBillData.tenantName + ' - Rs.' + currentBillData.totalBill
                });
            } catch (e) {
                if (e.name !== 'AbortError') {
                    alert('Sharing failed. Please try again.');
                }
            }
        } else {
            doc.save('Electricity_Bill_' + currentBillData.tenantName.replace(/\s+/g, '_') + '.pdf');
            alert('PDF downloaded. Please open WhatsApp and attach the file to share.');
        }
    }

    form.addEventListener('submit', function(e) {
        e.preventDefault();
        
        const date = dateInput.value;
        const tenantName = tenantNameInput.value.trim();
        const lastReading = parseInt(lastReadingInput.value);
        const currentReading = parseInt(currentReadingInput.value);
        
        if (!date || !tenantName || isNaN(lastReading) || isNaN(currentReading)) {
            showError('Please fill in all fields correctly.');
            return;
        }
        
        if (currentReading < lastReading) {
            showError('Current month reading must be greater than or equal to last month reading.');
            return;
        }
        
        if (lastReading < 0 || currentReading < 0) {
            showError('Reading values cannot be negative.');
            return;
        }
        
        const billData = calculateBill(lastReading, currentReading);
        
        currentBillData = {
            date,
            formattedDate: formatDate(date),
            tenantName,
            lastReading,
            currentReading,
            ...billData
        };
        
        displayResult(billData);
    });

    downloadPdfBtn.addEventListener('click', generatePdf);
    whatsappShareBtn.addEventListener('click', shareOnWhatsApp);
    closeBtn.addEventListener('click', clearForm);
});